const routes = {
  home: "/pages/index/index",
  account: "/pages/account/index/index",
  account_info: "/pages/account/information/information", 
  fapiao: "/pages/account/fapiao/fapiao",
  pets: "/pages/account/pets/pets",
  addpets: "/pages/account/addpets/addpets",
  address: "/pages/address/index/index",
  address_detail: "/pages/address/detail/detail",
  address_areas: "/pages/address/areas/areas",
  cart: "/pages/cart/cart",
  contacts: "/pages/contacts/index/index",
  contact: "/pages/contacts/detail/detail",
  edit_profile: "/pages/account/editprofile/editprofile",
  lottery: "/pages/lottery/index/index",
  lottery_detail: "/pages/lottery/detail/detail",
  offer_bourse: "/pages/offer/cellar/bourse/bourse",
  offer_cellar: "/pages/offer/cellar/cellar/cellar",
  offer_regular: "/pages/offer/regular/regular",
  orders: "/pages/orders/index/index",
  order: "/pages/orders/detail/detail",
  product: "/pages/product/product",
  recipes: "/pages/recipes/index/index",
  recipes_fav: "/pages/recipes/favourites/favourites",
  recipe: "/pages/recipes/detail/detail",
  vouchers: "/pages/vouchers/index/index",
  vouchers_select: "/pages/vouchers/select/select"
}

exports.routes = routes;